# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurment',
            name='user_id',
        ),
    ]
