# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0002_remove_measurment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurment',
            name='date',
            field=models.DateField(),
        ),
    ]
