# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0003_auto_20160830_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
